title = "Sqitch"
baseURL = "https://sqitch.org/"
languageCode = "en-us"
disableKinds = ["taxonomy", "taxonomyTerm", "RSS", "sitemap"]
copyright = "© Sqtich Hackers. This work is licensed under a Creative Commons Attribution 4.0 International License."
footnoteReturnLinkContents = "↩"

pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsStyle = "monokai"

[params]
  description = "Sqitch is the developer-friendly, confidence-inducing, platform-neutral database change management system."

[markup]
  # defaultMarkdownHandler = "blackfriday"

# Adding Goldmark config, but still using blackfriday, because the Common Mark
# standard requries only two spaces to indent a code block in a list item, while
# Markdown (and Blackfriday) require four. So with Goldmark we end up with code
# blocks inside list blocks with extra spaces at the beginning of each line.
# Complaints: https://twitter.com/theory/status/1262098089214717952
[markup.goldmark.renderer]
  unsafe = true
